### ISSUE TITLE
Git json file has content but the script returns "file empty"

### ISSUE THREAD

**Issue by bccrisan** [Akhliskun/firefox-infra-changelog#119]
**Describe the bug**
The script returns
`
File signingscript.json is empty. 
 Please check:[Link to commit](https://github.com/mozilla-releng/signingscript/commit/75e15a0b743977c70e1b2ad1651d267706063f02) for more details.
`
But the file has content and also the md file has previous content.

**To Reproduce**
Just run the script

**Expected behavior**
The script should return that error for cases in which the json repo file is empty

**Desktop (please complete the following information):**
 - OS:  All
 - Version: master (latest)

**Additional context**
The check is return in a `try-except` from `extract_json()` function.

` except KeyError:`
` print("File " + file + " is empty. \n Please check:" + repository_url + " for more details.\n")`
` pass`

**Comment by mutterroland** [comment]
For now , I removed try/except for debugging. Tried running the script for build-puppet only and it returns: Traceback (most recent call last):
  File "C:/Users/roland.mutter/Desktop/FireFox Ci - Copy/firefox-infra-changelog/client.py", line 425, in <module>
    generate_main_md_table("git_files")
  File "C:/Users/roland.mutter/Desktop/FireFox Ci - Copy/firefox-infra-changelog/client.py", line 333, in generate_main_md_table
    extract_json(json_files, path_to_files)
  File "C:/Users/roland.mutter/Desktop/FireFox Ci - Copy/firefox-infra-changelog/client.py", line 365, in extract_json
    commit_description = data[commit_number]["commit_message"]
KeyError: '4'

**Comment by mutterroland** [comment]
After some more investigation , I found why the bug is happening and when.

The one thing that is causing the bug is for commit_iterator in range(1, commits_per_repo + 1): in def extract_json(json_files, path_to_files, commits_per_repo=5):  .

As you can see , this function picks only the first 5 commits in the repo and write those in main_MD_table. The problems appears when , in json file, there are less than 5 commits . If there were only 3 commits, since we've last ran the script,  there isn't any Key:'4' or Key:'5' so it will result script running into the except KeyError.

**Comment by mutterroland** [comment]
My best guess is that we will never have a json with less than 5 commits because , we want to change json to append mode. Bug happens because we are overwriting .json files and it writes only commits based on the time frame we are requesting in for commit in
lastWeek = datetime.now() - timedelta(days=7) git.get_repo(repository_path).get_commits(since=lastWeek):

**Comment by mutterroland** [comment]
In my opinion this can be closed as we'll never encounter it again after going full append mode.
